// @ts-check
import {themes as prismThemes} from 'prism-react-renderer';
import fs from 'fs';
import path from 'path';
import {fileURLToPath} from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Load dynamic site config from JSON (generated by MCP build_docs)
const configPath = path.join(__dirname, 'site-config.json');
/** @type {Record<string, any>} */
let siteConfig = {};
if (fs.existsSync(configPath)) {
  siteConfig = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
}

const title = siteConfig.title || 'Documentation';
const tagline = siteConfig.tagline || '';
const url = siteConfig.url || 'http://localhost:3000';
const orgName = siteConfig.organizationName || '';
const projectName = siteConfig.projectName || 'docs';
const footerLinks = siteConfig.footerLinks || [];
const copyright = siteConfig.copyright || `Copyright © ${new Date().getFullYear()}. Built with Docusaurus.`;

/** @type {import('@docusaurus/types').Config} */
const config = {
  title,
  tagline,
  favicon: 'img/favicon.ico',

  future: {
    v4: true,
  },

  url,
  baseUrl: '/',

  organizationName: orgName,
  projectName,

  onBrokenLinks: 'warn',

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          sidebarPath: './sidebars.js',
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      }),
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      colorMode: {
        respectPrefersColorScheme: true,
      },
      navbar: {
        title,
        items: [
          {
            type: 'docSidebar',
            sidebarId: 'docs',
            position: 'left',
            label: 'Documentation',
          },
        ],
      },
      footer: {
        style: 'dark',
        links: footerLinks,
        copyright,
      },
      prism: {
        theme: prismThemes.github,
        darkTheme: prismThemes.dracula,
      },
    }),
};

export default config;
