// @ts-check
import {themes as prismThemes} from 'prism-react-renderer';
import fs from 'fs';
import path from 'path';
import {fileURLToPath} from 'url';
import {createRequire} from 'module';

const require = createRequire(import.meta.url);

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Load dynamic site config from JSON (generated by MCP build_docs)
const configPath = path.join(__dirname, 'site-config.json');
/** @type {Record<string, any>} */
let siteConfig = {};
if (fs.existsSync(configPath)) {
  siteConfig = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
}

const title = siteConfig.title || 'Documentation';
const tagline = siteConfig.tagline || '';
const url = siteConfig.url || 'http://localhost:3000';
const orgName = siteConfig.organizationName || '';
const projectName = siteConfig.projectName || 'docs';
const footerLinks = siteConfig.footerLinks || [];
const copyright = siteConfig.copyright || `Copyright © ${new Date().getFullYear()}. Built with Docusaurus.`;

// Check if OpenAPI spec exists
const openapiPath = path.join(__dirname, 'openapi.json');
const hasOpenAPI = fs.existsSync(openapiPath);

/** @type {import('@docusaurus/types').Config} */
const config = {
  title,
  tagline,
  favicon: 'img/favicon.ico',

  future: {
    v4: true,
  },

  url,
  baseUrl: '/',

  organizationName: orgName,
  projectName,

  onBrokenLinks: 'warn',

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          sidebarPath: './sidebars.js',
          docItemComponent: '@theme/ApiItem',
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      }),
    ],
  ],

  plugins: [
    ...(hasOpenAPI ? [
      [
        'docusaurus-plugin-openapi-docs',
        /** @type {import('docusaurus-plugin-openapi-docs').Options} */
        ({
          id: 'api',
          docsPluginId: 'default',
          config: {
            api: {
              specPath: './openapi.json',
              outputDir: './docs/api-reference',
              sidebarOptions: {
                groupPathsBy: 'tag',
              },
            },
          },
        }),
      ],
    ] : []),
    function webpackPolyfillPlugin() {
      return {
        name: 'webpack-polyfill-plugin',
        configureWebpack() {
          return {
            resolve: {
              fallback: {
                path: require.resolve('path-browserify'),
              },
            },
          };
        },
      };
    },
  ],

  themes: ['docusaurus-theme-openapi-docs'],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      colorMode: {
        respectPrefersColorScheme: true,
      },
      navbar: {
        title,
        items: [
          {
            type: 'docSidebar',
            sidebarId: 'docs',
            position: 'left',
            label: 'Documentation',
          },
          ...(hasOpenAPI ? [{
            type: 'docSidebar',
            sidebarId: 'api',
            position: 'left',
            label: 'API Reference',
          }] : []),
        ],
      },
      footer: {
        style: 'dark',
        links: footerLinks,
        copyright,
      },
      prism: {
        theme: prismThemes.github,
        darkTheme: prismThemes.dracula,
      },
    }),
};

export default config;
